title: "Ritwik Saraf"
description: "Portfolio of Ritwik Saraf"
baseurl: ""  # Keep it empty for GitHub Pages
url: "https://ritwiksaraf.github.io"

author: "Ritwik Saraf"

exclude:
  - demo/
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 5
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
